### PR TITLE
Minor update of FRENCH translation for info_acp_quicklanguage.php file

### PR DESCRIPTION
**Pull request by Galixte**
Minor update of FRENCH translation for info_acp_quicklanguage.php file

### CODE REVIEW

**Comment by alg5** [comment]
thank's a lot :)

**Comment by alg5** [comment]
now ext didn't pass validation :(

**Comment by Galixte** [comment]
i check this ...

**Comment by Galixte** [comment]
On travis fails i don't see anything about my PR.

However I saw this:
https://twitter.com/traviscistatus/status/592902357144498176
https://www.traviscistatus.com/incidents/h91j8ft0qs2l

**Comment by Galixte** [comment]
Oh sorry, i did not understand what you were talking, you were talking about the phpBB validation ? I'm not a coder unfortunately, but you have some recommendations for your unvalidate extension ?

**Pull request merged**
