### PR TITLE
Uniform display in ACP settings

### PR DESCRIPTION
**Pull request by Galixte**
Update for /ext/alg/quicklanguage/adm/style/acp_quicklanguage.html

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @alg5, this modification changes the display of link to the left corner because there are some extensions which are displayed already in right corner of messages.

**Comment by alg5** [comment]
Galixte, but some another extensions use left corner. Each admin after set this ext may use CSS to show this in a best position

**Comment by Galixte** [comment]
Ok fine.

**Comment by Galixte** [comment]
Hi @alg5,

i have doing a mistake in the explaination of my modification. It's about a fix to the correct displaying in ACP settings page for this extension. 

Take a look.

**Pull request merged**
